Use PlayerProfile instead of GameProfile to set skull texture
stefvanschie/IF pull request #652
Opened 2023-11-01 21:31 UTC by vicen621

I am making this pull request because I was having an issue with the Label Pane. The problem was as follows: when trying to create a label pane, I was getting the following error:
```
java.lang.ExceptionInInitializerError: null
	at io.github.vicen621.advanceduhc.scenarios.ScenarioManagerImpl.lambda$getScenInventory$23(ScenarioManagerImpl.java:332) ~[advanced-uhc-plugin-1.2.0.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-260]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-260]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Profile name must not be null
	at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?]
	at io.github.vicen621.advanceduhc.libs.inventoryframework.util.SkullUtil.setSkull(SkullUtil.java:54) ~[advanced-uhc-plugin-1.2.0.jar:?]
	at io.github.vicen621.advanceduhc.libs.inventoryframework.util.SkullUtil.getSkull(SkullUtil.java:41) ~[advanced-uhc-plugin-1.2.0.jar:?]
	at io.github.vicen621.advanceduhc.libs.inventoryframework.font.CSVFont.lambda$new$1(CSVFont.java:46) ~[advanced-uhc-plugin-1.2.0.jar:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at io.github.vicen621.advanceduhc.libs.inventoryframework.font.CSVFont.<init>(CSVFont.java:46) ~[advanced-uhc-plugin-1.2.0.jar:?]
	at io.github.vicen621.advanceduhc.libs.inventoryframework.font.util.Font.<clinit>(Font.java:29) ~[advanced-uhc-plugin-1.2.0.jar:?]
	... 7 more
```
Upon investigating the cause, it seems that in the new versions, GameProfiles cannot be created with a null name, so the first thing I did was create the GameProfile with an empty string. This worked, but I still got the following message:
```
Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
```
So, after doing some research, I found that the way to resolve it was by using PlayerProfiles. This fixes the error I was experiencing with the labels.

Feel free to reach out for any questions. Thank you in advance!

2024-01-21 18:34 UTC, stefvanschie requested changes
Thank you for your pull request. Unfortunately `Server#createPlayerProfile(UUID)` is a pretty recent API addition which would mean versions 1.14-1.17 would no longer work. The warning you're getting if you only set the name to an empty string seems to be due to the `serializedProfile` field not being set. I think it'd be best if the current reflection code was kept to ensure compatibility, but this field also being set to get rid of the warning.

Also note that the parameter change in the `setSkull` method would constitute a breaking change. Preferably this should be kept as it was, or you should add your new method alongside the other one and deprecate the current one (as I agree the method should take a `SkullMeta` rather than an `ItemMeta`).
Please also avoid bumping versions yourself, this makes it more difficult to merge PRs if we want to merge them in a different version or if we already bumped the version due to other code already being present.

If you could make these changes, then I'll gladly accept your PR. If you don't want to do this, that's of course also fine, but in that case please let me know. That way I know to make these changes myself.

2024-02-20 22:55 UTC, vicen621 commented
Hey, sorry for the wait, I haven’t seen your answer. 
I was trying to fix what you told me and realized that the "serializedProfile" field is a NBTTagCompound, so it’s in the NMS package. Can you think of any way to set the value of this field without having to import the NMS package?

2024-02-20 22:56 UTC, vicen621 commented
Hey, sorry for the wait, I haven’t seen your answer.
I was trying to fix what you told me and realized that the "serializedProfile" field is a NBTTagCompound, so it’s in the NMS package. Can you think of any way to set the value of this field without having to import the NMS package?

2024-03-01 20:19 UTC, stefvanschie commented
Probably the best way to do this is by using reflection, similar to how the `profile` field is set via reflection.

2024-03-16 20:53 UTC, stefvanschie commented
Closing this as #814 was merged, which addresses the same issue.

2024-03-16 20:53 UTC, closed without merging